### ISSUE TITLE
Подготовить проект для вёрстки

### ISSUE THREAD

**Issue by Yourloff** [Yourloff/yourloff_develop#3]
- Взять из макета **все картинки** и сохранить в каталоге `/img`.
Фоновые картинки в формате *jpg, иконки и картинки без фона в формате *png.

- **Добавить шрифты** из макета в каталог `/fonts`. Для этого воспользоваться сервисом https://transfonter.org/.
Конвертировать TTF в следующие форматы: EOT, WOFF и WOFF2. Это нужно чтобы шрифты 100% отображались на разных устройствах и браузерах.

**Comment by proskurekov** [comment]
Возьму задачу

**Comment by proskurekov** [comment]
нет смысла конвертировать TTF т.к он почти во всех браузерах поддерживается кроме IE, но нам он зачем ?
